#pragma once

namespace MoonJuice {
  enum class Operator : uint8_t {
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Concat,
    Length,
    Not,
    And,
    Or,
    OptionalCoalesce,
    Equals,
    NotEquals,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    Pipe,
    Index,
    OptionalIndex,
    IndexExpression,
    OptionalIndexExpression,
    Call,
    OptionalCall,
    Assignment,
    BitwiseNot,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    LeftShift,
    RightShift,
  };
}
